### ISSUE TITLE
Video of the 2021 conference is unavailable

### ISSUE THREAD

**Issue by nth-block** [collabnix/osconf#19]
The video seems to be _private_

![image](https://user-images.githubusercontent.com/20584285/114590681-b3cd1c00-9ca6-11eb-9098-9d02cca76b89.png)

Can this be made public please?

**Comment by collabnix** [comment]
Fixed. Check it out.

**Comment by nth-block** [comment]
@collabnix , nope, still does not work. I am using the https://www.youtube.com/watch?v=Eo-wsdrtn-E link from the README.md in the repo.

**Comment by ajeetraina** [comment]
Access this https://www.youtube.com/watch?v=gbJvMcVgPkg&t=7709s

**Comment by nth-block** [comment]
It works now. Thanks a lot..
